# Generated by Django 5.0.6 on 2024-07-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('FrontEnd', 'Developer'), ('life', 'Lifestyle'), ('edu', 'Education'), ('ent', 'Entertainment')], max_length=20, null=True),
        ),
    ]
