# Generated by Django 5.0.6 on 2024-07-08 10:18

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Front-End', 'FrontEnd'), ('Back-End', 'Backend'), ('edu', 'Education'), ('ent', 'Entertainment')], max_length=26, null=True),
        ),
    ]
