# Generated by Django 5.0.6 on 2024-07-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('Front-End', 'FrontEnd'), ('Back-End', 'Backend'), ('edu', 'Education'), ('ent', 'Entertainment')], max_length=30, null=True),
        ),
    ]
